name: abaplint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  abaplint:
    name: abaplint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Run abaplint
        run: |
          npm -g install @abaplint/cli
          abaplint --format codeframe
